In [40]:
import random

In [50]:
import random
randomlist = []
for i in range(0,2500):
    n = random.randint(0,4)
    randomlist.append(n)
print(randomlist)

[2, 2, 3, 1, 2, 3, 4, 1, 1, 2, 3, 1, 1, 2, 4, 2, 3, 4, 0, 1, 0, 3, 1, 0, 3, 2, 2, 0, 0, 2, 4, 0, 4, 1, 0, 2, 0, 4, 0, 1, 4, 1, 2, 0, 1, 1, 4, 3, 2, 4, 4, 4, 3, 4, 0, 3, 1, 0, 1, 1, 4, 1, 1, 1, 1, 0, 0, 4, 2, 0, 3, 2, 1, 3, 0, 4, 3, 4, 3, 1, 1, 2, 0, 4, 3, 1, 0, 0, 4, 1, 4, 1, 0, 0, 0, 0, 1, 3, 1, 3, 3, 0, 0, 0, 1, 4, 1, 3, 4, 4, 1, 4, 3, 0, 4, 3, 2, 3, 3, 3, 2, 0, 0, 1, 1, 1, 3, 2, 0, 4, 4, 2, 4, 2, 2, 0, 0, 0, 2, 3, 4, 3, 3, 0, 4, 4, 0, 2, 1, 0, 1, 0, 4, 3, 0, 4, 3, 0, 0, 0, 3, 1, 4, 0, 3, 0, 4, 3, 3, 3, 0, 4, 1, 1, 0, 3, 2, 1, 0, 2, 3, 3, 0, 0, 4, 4, 3, 4, 2, 2, 4, 3, 3, 4, 3, 1, 3, 0, 4, 0, 0, 1, 4, 3, 3, 3, 3, 1, 1, 3, 4, 1, 0, 1, 2, 4, 0, 0, 2, 3, 4, 4, 3, 0, 4, 1, 1, 1, 0, 1, 4, 0, 2, 0, 2, 2, 2, 4, 4, 0, 4, 0, 0, 2, 4, 4, 4, 4, 1, 3, 1, 4, 3, 4, 0, 4, 3, 1, 4, 3, 1, 2, 2, 2, 2, 4, 3, 2, 0, 3, 0, 2, 1, 2, 3, 4, 4, 2, 1, 2, 1, 3, 2, 2, 3, 3, 4, 3, 1, 4, 3, 2, 0, 1, 1, 1, 2, 1, 3, 4, 2, 3, 4, 3, 3, 2, 4, 2, 1, 1, 2, 2, 4, 4, 2, 4, 1, 1, 2, 0, 2, 0, 4, 4, 0, 2, 0, 3, 2, 4, 0, 0, 0, 1, 1, 2, 0, 4, 1, 3, 2, 2, 4, 4, 0, 2, 1, 3, 3, 1, 2, 3, 2, 0, 1, 2, 4, 3, 1, 4, 3, 0, 3, 0, 4, 0, 3, 4, 4, 1, 0, 1, 2, 4, 3, 1, 1, 1, 2, 0, 3, 0, 0, 4, 4, 3, 1, 4, 3, 4, 2, 0, 2, 0, 3, 1, 2, 0, 2, 1, 2, 3, 2, 0, 3, 3, 0, 3, 4, 1, 0, 2, 0, 3, 2, 2, 1, 0, 2, 4, 1, 3, 1, 0, 3, 3, 0, 4, 1, 0, 2, 2, 1, 2, 2, 1, 2, 1, 1, 0, 3, 1, 2, 1, 2, 4, 0, 1, 3, 2, 1, 4, 0, 0, 0, 2, 2, 2, 3, 1, 3, 3, 4, 0, 3, 4, 3, 1, 2, 3, 4, 0, 1, 0, 3, 4, 3, 2, 1, 2, 2, 0, 4, 3, 4, 3, 2, 4, 1, 2, 3, 2, 2, 3, 1, 0, 3, 1, 1, 1, 2, 1, 2, 1, 3, 1, 4, 3, 2, 2, 3, 3, 2, 1, 4, 1, 0, 2, 0, 2, 4, 2, 1, 1, 3, 1, 1, 0, 2, 4, 0, 4, 1, 0, 2, 4, 1, 0, 2, 4, 0, 2, 1, 3, 2, 3, 3, 4, 4, 0, 2, 2, 0, 4, 4, 4, 3, 0, 0, 3, 0, 2, 2, 1, 0, 3, 0, 1, 0, 0, 1, 3, 3, 4, 3, 1, 1, 4, 0, 0, 2, 3, 0, 0, 3, 2, 2, 4, 1, 0, 1, 2, 0, 2, 0, 3, 3, 4, 2, 3, 2, 4, 2, 1, 2, 0, 3, 3, 0, 0, 3, 2, 0, 2, 3, 3, 2, 2, 4, 0, 0, 3, 2, 2, 1, 2, 3, 4, 2, 3, 2, 2, 3, 1, 3, 3, 3, 2, 2, 4, 2, 4, 2, 3, 1, 1, 1, 3, 0, 3, 2, 3, 4, 2, 4, 1, 4, 3, 3, 1, 3, 0, 0, 3, 1, 0, 4, 3, 3, 1, 0, 4, 1, 2, 2, 3, 0, 3, 2, 0, 0, 1, 1, 1, 1, 1, 4, 2, 0, 0, 1, 1, 0, 1, 4, 2, 3, 0, 2, 2, 2, 3, 3, 4, 0, 0, 2, 3, 3, 1, 1, 0, 2, 0, 1, 0, 3, 3, 2, 0, 4, 3, 2, 4, 3, 0, 0, 0, 2, 1, 1, 3, 2, 1, 1, 3, 0, 4, 4, 0, 4, 3, 1, 1, 3, 3, 0, 4, 0, 3, 0, 4, 4, 1, 2, 2, 2, 2, 4, 2, 4, 0, 3, 2, 4, 4, 4, 0, 3, 1, 0, 4, 2, 2, 1, 3, 3, 0, 2, 1, 2, 2, 1, 4, 1, 1, 0, 4, 4, 2, 3, 4, 0, 0, 0, 2, 4, 3, 1, 0, 3, 2, 1, 1, 1, 2, 3, 0, 3, 3, 1, 4, 4, 4, 3, 3, 3, 1, 2, 2, 0, 4, 3, 1, 1, 3, 3, 4, 4, 2, 4, 2, 1, 2, 4, 4, 1, 4, 2, 2, 4, 3, 3, 0, 3, 0, 4, 1, 4, 4, 0, 2, 4, 1, 1, 4, 1, 1, 0, 3, 0, 4, 0, 4, 4, 0, 2, 0, 3, 3, 1, 3, 3, 3, 3, 2, 3, 1, 2, 2, 1, 4, 0, 2, 3, 2, 4, 2, 3, 2, 3, 0, 4, 1, 2, 4, 2, 3, 3, 3, 0, 0, 1, 1, 2, 0, 3, 3, 1, 1, 1, 0, 1, 2, 2, 4, 1, 4, 2, 0, 1, 0, 2, 1, 3, 2, 4, 3, 3, 2, 4, 3, 1, 3, 0, 3, 4, 4, 3, 2, 0, 2, 1, 0, 2, 3, 1, 1, 4, 4, 0, 0, 4, 1, 4, 0, 2, 4, 2, 0, 2, 3, 3, 0, 1, 1, 2, 1, 0, 1, 2, 3, 0, 2, 1, 2, 3, 0, 4, 4, 2, 2, 3, 4, 4, 0, 4, 0, 2, 4, 1, 4, 4, 2, 3, 4, 0, 4, 0, 2, 3, 2, 3, 1, 4, 3, 3, 1, 0, 4, 4, 1, 2, 2, 2, 2, 2, 4, 3, 1, 2, 1, 0, 1, 1, 3, 2, 2, 4, 1, 1, 0, 3, 3, 2, 0, 0, 0, 3, 4, 0, 0, 4, 2, 1, 4, 0, 1, 4, 1, 3, 3, 2, 3, 4, 4, 0, 3, 0, 4, 2, 0, 3, 4, 4, 4, 2, 1, 3, 2, 1, 0, 2, 0, 2, 3, 4, 4, 4, 1, 1, 3, 3, 4, 3, 2, 1, 2, 1, 2, 3, 1, 2, 3, 4, 0, 2, 2, 4, 4, 4, 3, 3, 2, 3, 4, 4, 4, 3, 4, 4, 4, 2, 2, 3, 3, 4, 2, 1, 4, 1, 2, 3, 4, 3, 3, 4, 3, 4, 1, 3, 1, 2, 2, 2, 3, 4, 2, 3, 3, 4, 4, 2, 2, 0, 4, 2, 2, 4, 2, 3, 2, 4, 4, 2, 4, 0, 2, 0, 2, 1, 4, 1, 3, 0, 0, 2, 2, 0, 2, 0, 3, 1, 2, 2, 4, 2, 4, 4, 2, 1, 0, 3, 3, 3, 1, 3, 2, 3, 3, 3, 2, 1, 4, 2, 2, 4, 1, 4, 1, 1, 4, 4, 0, 4, 3, 4, 3, 3, 0, 1, 2, 3, 2, 1, 4, 2, 1, 4, 2, 4, 0, 2, 4, 0, 4, 2, 2, 4, 0, 1, 0, 3, 1, 0, 0, 1, 0, 4, 3, 3, 3, 1, 2, 2, 4, 3, 4, 3, 3, 3, 3, 3, 1, 3, 3, 3, 4, 4, 1, 0, 1, 2, 3, 2, 2, 2, 4, 4, 1, 1, 1, 2, 2, 4, 0, 1, 4, 3, 4, 4, 3, 3, 1, 3, 0, 3, 3, 4, 2, 0, 4, 0, 2, 0, 3, 4, 2, 1, 2, 2, 0, 0, 3, 2, 1, 2, 2, 1, 3, 3, 2, 1, 3, 2, 2, 0, 3, 3, 0, 2, 3, 0, 1, 2, 0, 3, 0, 2, 2, 1, 0, 3, 4, 1, 2, 4, 1, 3, 3, 3, 4, 1, 2, 2, 1, 1, 3, 1, 2, 0, 3, 3, 1, 1, 0, 0, 2, 2, 0, 3, 0, 3, 4, 2, 4, 0, 1, 0, 4, 2, 0, 4, 3, 0, 2, 2, 3, 0, 3, 0, 3, 2, 3, 3, 0, 0, 2, 1, 3, 4, 3, 4, 1, 1, 0, 4, 4, 0, 3, 4, 0, 2, 0, 1, 0, 2, 0, 4, 4, 3, 1, 4, 1, 3, 4, 4, 1, 2, 4, 2, 1, 3, 1, 1, 4, 4, 4, 1, 2, 4, 0, 0, 3, 4, 0, 4, 0, 0, 2, 0, 1, 0, 3, 3, 0, 1, 0, 4, 3, 4, 2, 4, 1, 0, 4, 1, 4, 4, 0, 4, 2, 2, 0, 4, 1, 1, 2, 4, 2, 3, 4, 3, 2, 1, 1, 1, 1, 3, 4, 1, 2, 1, 2, 2, 3, 3, 4, 2, 0, 4, 4, 1, 2, 4, 4, 1, 0, 0, 4, 1, 2, 1, 4, 3, 0, 3, 0, 1, 2, 2, 0, 3, 3, 2, 3, 2, 2, 3, 2, 1, 4, 1, 4, 2, 0, 1, 4, 0, 2, 0, 4, 2, 2, 4, 3, 4, 3, 0, 1, 3, 1, 0, 0, 2, 0, 3, 0, 4, 3, 4, 4, 4, 3, 1, 2, 1, 1, 0, 1, 1, 4, 3, 2, 4, 3, 0, 2, 0, 1, 1, 0, 3, 1, 3, 4, 3, 4, 1, 2, 3, 4, 3, 2, 2, 2, 1, 1, 4, 4, 3, 3, 1, 4, 3, 1, 1, 1, 0, 0, 0, 0, 3, 0, 3, 0, 4, 2, 3, 4, 3, 1, 2, 3, 4, 0, 2, 4, 0, 0, 0, 3, 0, 3, 1, 1, 1, 1, 4, 0, 1, 1, 2, 2, 1, 3, 3, 3, 2, 2, 1, 3, 0, 0, 4, 2, 3, 2, 3, 4, 4, 1, 1, 3, 3, 0, 1, 3, 4, 1, 2, 2, 4, 3, 2, 4, 3, 2, 3, 3, 1, 3, 4, 4, 3, 3, 0, 4, 2, 4, 1, 2, 2, 0, 0, 2, 1, 0, 2, 4, 4, 0, 3, 0, 0, 1, 4, 1, 0, 1, 3, 0, 1, 2, 4, 0, 1, 1, 1, 4, 3, 3, 1, 4, 2, 2, 0, 0, 3, 3, 0, 2, 0, 0, 2, 0, 4, 1, 3, 2, 2, 3, 1, 0, 3, 0, 4, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 4, 3, 1, 0, 3, 1, 3, 4, 2, 0, 0, 1, 0, 2, 0, 2, 3, 0, 3, 3, 3, 0, 2, 4, 0, 0, 3, 1, 0, 1, 0, 4, 3, 0, 4, 4, 4, 3, 4, 2, 0, 1, 2, 3, 3, 0, 1, 4, 4, 2, 0, 2, 2, 0, 1, 0, 1, 3, 3, 2, 0, 3, 1, 3, 0, 2, 1, 2, 4, 0, 3, 3, 4, 2, 1, 1, 3, 4, 1, 3, 1, 2, 2, 3, 1, 3, 3, 3, 3, 0, 1, 4, 4, 2, 1, 0, 1, 1, 3, 4, 0, 2, 2, 3, 3, 2, 0, 1, 3, 4, 2, 4, 0, 0, 0, 4, 3, 3, 3, 3, 4, 4, 2, 4, 3, 0, 4, 0, 1, 2, 4, 1, 3, 0, 4, 1, 4, 4, 0, 3, 0, 2, 3, 0, 0, 2, 4, 3, 3, 3, 3, 2, 0, 4, 4, 1, 2, 3, 4, 4, 2, 1, 1, 0, 4, 3, 4, 3, 2, 3, 2, 0, 2, 3, 3, 2, 0, 1, 2, 4, 4, 3, 1, 4, 2, 4, 0, 2, 4, 2, 1, 4, 1, 4, 1, 3, 0, 3, 2, 1, 0, 0, 3, 0, 4, 0, 3, 4, 0, 1, 3, 1, 4, 4, 1, 1, 4, 4, 0, 3, 2, 1, 2, 4, 2, 4, 3, 3, 2, 4, 1, 0, 2, 3, 4, 0, 0, 2, 1, 4, 4, 3, 2, 1, 0, 3, 4, 1, 1, 1, 2, 2, 3, 0, 2, 1, 2, 2, 0, 4, 0, 1, 3, 3, 1, 0, 4, 2, 2, 3, 3, 1, 0, 2, 3, 0, 1, 1, 4, 0, 0, 2, 0, 4, 4, 0, 1, 1, 3, 0, 1, 0, 3, 2, 2, 1, 3, 3, 0, 0, 3, 1, 3, 3, 0, 3, 2, 2, 4, 1, 0, 1, 0, 2, 2, 1, 1, 1, 3, 1, 1, 0, 1, 0, 0, 2, 2, 0, 0, 0, 2, 1, 2, 2, 0, 3, 1, 0, 1, 3, 2, 0, 0, 2, 1, 1, 2, 0, 2, 3, 1, 3, 3, 2, 1, 1, 1, 4, 2, 1, 4, 3, 2, 2, 4, 0, 4, 0, 2, 2, 0, 3, 4, 3, 0, 1, 0, 2, 4, 1, 1, 2, 2, 1, 0, 2, 4, 3, 3, 2, 2, 3, 4, 4, 0, 4, 3, 2, 3, 4, 4, 0, 4, 0, 3, 1, 1, 1, 3, 4, 3, 1, 1, 0, 1, 2, 1, 3, 3, 4, 0, 0, 2, 4, 3, 0, 2, 4, 3, 1, 0, 0, 1, 2, 3, 4, 2, 0, 0, 2, 2, 2, 0, 4, 3, 3, 2, 2, 3, 2, 4, 2, 4, 0, 0, 1, 2, 1, 2, 2, 1, 4, 1, 2, 2, 0, 4, 3, 4, 2, 3, 0, 2, 3, 3, 4, 4, 3, 3, 2, 4, 2, 4, 3, 3, 3, 3, 1, 3, 4, 3, 0, 0, 0, 2, 2, 0, 1, 3, 3, 3, 1, 2, 3, 1, 0, 1, 4, 3, 3, 0, 2, 4, 2, 1, 1, 2, 3, 4, 3, 2, 1, 4, 0, 4, 3, 3, 3, 4, 2, 0, 0, 4, 4, 2, 1, 1, 4, 4, 2, 3, 4, 3, 1, 0, 3, 1, 0, 2, 0, 2, 2, 2, 2, 0, 4, 1, 3, 1, 2, 3, 1, 4, 0, 3, 4, 0, 1, 1, 1, 4, 4, 4, 1, 2, 3, 1, 0, 0, 1, 1, 2, 3, 1, 4, 0, 1, 4, 2, 4, 2, 1, 0, 0, 4, 2, 4, 3, 4, 4, 1, 3, 4, 0, 4, 4, 0, 0, 2, 3, 4, 2, 3, 4, 1, 2, 3, 2, 2, 3, 1, 1, 3, 2, 3, 4, 1, 2, 4, 0, 1, 2, 0, 4, 0, 3, 4, 0, 2, 1, 3, 3, 2, 1, 4, 3, 1, 2, 4, 2, 1, 4, 3, 2, 2, 0, 2, 1, 3, 1, 1, 2, 2, 1, 2, 4, 1, 0, 1, 3, 2, 0, 2, 3, 1, 4, 4, 3, 2, 3, 4, 4, 2, 1, 0, 0, 4, 3, 3, 2, 4, 3, 3, 0, 0, 3, 4, 4, 3, 3, 1, 3, 3, 3, 0, 4, 0, 4, 4, 4, 1, 1, 3, 4, 2, 4, 3, 0, 4, 2, 2, 3, 2, 3, 0, 1, 0, 1, 1, 2, 3, 3, 4, 4, 0, 0, 2, 4, 2, 2, 4, 2, 0, 3, 2, 4, 1, 2, 4, 0, 2, 0, 3]

In [51]:
for i in range(0,2500):
    if randomlist[i] == 2:
        randomlist[i] = 0
    if randomlist[i] == 3:
        randomlist[i] = 1
    if randomlist[i] == 4:
        randomlist[i] = 1

In [52]:
L8 = randomlist

In [53]:
_list = [L1,L2,L3,L4,L5,L6,L7,L8]

In [58]:
import pandas as pd
import numpy as np

In [60]:
_list = np.array(_list)

In [61]:
df = pd.DataFrame(data=_list.T, columns=['Intro01','Intro02','Intro03','Intro04','Intro05','Intro06','Intro07','Intro08'])

In [62]:
df

      Intro01  Intro02  Intro03  Intro04  Intro05  Intro06  Intro07  Intro08
0           0        1        0        0        0        1        0        0
1           1        0        0        0        1        1        0        0
2           1        0        1        1        1        1        1        1
3           0        0        0        0        0        0        0        1
4           0        0        0        0        0        1        0        0
...       ...      ...      ...      ...      ...      ...      ...      ...
2495        1        0        0        0        0        0        0        1
2496        1        0        0        0        0        1        1        0
2497        1        1        0        0        0        0        1        0
2498        0        0        0        0        1        0        0        0
2499        0        1        0        1        1        0        0        1

[2500 rows x 8 columns]

In [65]:
df.to_csv('UCB.csv',index=False)